server:
  port: ${PORT:9008}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:1@localhost:8761}/eureka/

---
spring:
  config:
    activate:
      on-profile: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80